### ISSUE TITLE
passing path as input

### ISSUE THREAD

**Issue by silas-x** [soteria-bc/action-pilot-test#1]
Would be great to add a feature where you can pass program path to the job, e.g. if you are running the job against a mono repo, or if you have non-Solana programs in the same repo.

Something along the lines of this, where default is root folder:

`path:
    description: "Configure the job to run tests against a specific program"
    required: false
    default: "."`

Thanks!

**Comment by jihangli11** [comment]
Thank you. Very good suggestion! We've added this feature and it is available right now. Please see the README.
