### ISSUE TITLE
Increase warning cap

### ISSUE THREAD

**Issue by silas-x** [soteria-bc/action-pilot-test#2]
Hey team

In the free version, there's a cap of 25 warnings/findings per cap. In Coderrect, you used to be able to overrule that with your own config, but that doesn't seem to work for Soteria.

In the premium web version, the cap is gone and you can report on more than 25 issues - great! But, with this action, the limit of 25 is back. Is there a way to remove that, or possibly add it as an input variable to specify it?

Nb: appreciate it's not great to have more than 25 issues in the first place, but with a relatively high rate of false positives and accepted rounding warnings (but not yet formally ignores), a large contract can easily hit 25.

Thanks
Silas

**Comment by coderrect** [comment]
Hi Silas, added now

1. set "raceLimit" to the cap in ```coderrect.json```, e.g.,
```
{
    "raceLimit": 99
}
```


2. add "--no-limit" to soteria cli:, e.g.

```soteria --no-limit .```

**Comment by silas-x** [comment]
thanks @coderrect but there seems to be a cap on this action at 25, which I wouldn't be able to change myself?

**Comment by coderrect** [comment]
thanks again @silas-x . for "pro" action, now cap is reset to a large enough number. we haven't opened user configurable options, it is under frequent iteration currently.
